[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
argon2 = "0.5.3"
atomic-write-file = { version = "0.3.0", features = ["unnamed-tmpfile"] }
axum = { version = "0.8.8", features = ["macros"] }
axum-extra = { version = "0.12.5", features = ["cookie"] }
chrono = { version = "0.4.43", features = ["serde"] }
garde = { version = "0.22.1", features = ["derive"] }
log = "0.4.29"
rand = "0.9.2"
# Only needed as a dependency for argon2 salt generation
#  - Some refactoring on their side means the getrandom feature isn't enabled and they won't fix it on their side
rand_core = { version = "0.6.4", features = ["getrandom"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_with = "3.16.1"
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["fs", "macros", "process", "rt-multi-thread", "sync"] }
tower-http = { version = "0.6.8", features = ["fs", "trace"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
